# Generated by Django 5.2.6 on 2025-09-09 16:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Vendor company name", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for the vendor"
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("medical_device", "Medical Device Supplier"),
                            ("pharmaceutical", "Pharmaceutical"),
                            ("it_services", "IT Services"),
                            ("facility_services", "Facility Services"),
                            ("consulting", "Consulting"),
                            ("staffing", "Staffing Agency"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of vendor/service provider",
                        max_length=50,
                    ),
                ),
                (
                    "primary_contact_name",
                    models.CharField(
                        help_text="Primary contact person at vendor", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Primary contact phone", max_length=20),
                ),
                ("address", models.TextField(help_text="Vendor's business address")),
                ("website", models.URLField(blank=True, help_text="Vendor's website")),
                (
                    "risk_score",
                    models.IntegerField(
                        default=50,
                        help_text="Overall risk score (0-100, lower is better)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("critical", "Critical Risk"),
                            ("high", "High Risk"),
                            ("medium", "Medium Risk"),
                            ("low", "Low Risk"),
                            ("minimal", "Minimal Risk"),
                        ],
                        default="medium",
                        help_text="Overall risk classification",
                        max_length=20,
                    ),
                ),
                (
                    "handles_phi",
                    models.BooleanField(
                        default=False,
                        help_text="Does this vendor handle Protected Health Information?",
                    ),
                ),
                (
                    "baa_signed",
                    models.BooleanField(
                        default=False, help_text="Business Associate Agreement signed?"
                    ),
                ),
                (
                    "baa_signed_date",
                    models.DateField(
                        blank=True, help_text="Date BAA was signed", null=True
                    ),
                ),
                (
                    "baa_expiry_date",
                    models.DateField(
                        blank=True, help_text="BAA expiration date", null=True
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Fully Compliant"),
                            ("partial", "Partially Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("pending", "Pending Review"),
                            ("expired", "Compliance Expired"),
                        ],
                        default="pending",
                        help_text="Current compliance status",
                        max_length=20,
                    ),
                ),
                (
                    "last_assessment_date",
                    models.DateField(
                        blank=True, help_text="Date of last risk assessment", null=True
                    ),
                ),
                (
                    "next_assessment_date",
                    models.DateField(
                        blank=True,
                        help_text="Scheduled date for next assessment",
                        null=True,
                    ),
                ),
                (
                    "services_provided",
                    models.TextField(
                        help_text="Description of services this vendor provides"
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a critical vendor that could impact patient care?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this vendor currently active?"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this vendor (not visible to vendor)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The healthcare organization this vendor serves",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("organization", "slug")},
            },
        ),
        migrations.CreateModel(
            name="VendorContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this the primary contact?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_contacts",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "name"],
            },
        ),
    ]
