# Generated by Django 5.2.6 on 2025-09-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="What action was performed (e.g., 'viewed_patient_record')",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="The type of object that was affected",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the affected object",
                        max_length=255,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="JSON field for additional audit details"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
