# Generated by Django 5.2.6 on 2025-09-12 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                (
                    "due_date",
                    models.DateField(help_text="When the vendor must complete this"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending - Not Started"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted - Awaiting Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected - Needs Revision"),
                            ("expired", "Expired - Past Due"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "started_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When vendor started the assessment",
                        null=True,
                    ),
                ),
                (
                    "submitted_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When vendor submitted responses",
                        null=True,
                    ),
                ),
                (
                    "reviewed_date",
                    models.DateTimeField(
                        blank=True, help_text="When assessment was reviewed", null=True
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        help_text="Final score as percentage",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(
                        blank=True, help_text="Did they pass the assessment?", null=True
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes from reviewer"
                    ),
                ),
                (
                    "vendor_notes",
                    models.TextField(blank=True, help_text="Notes from vendor"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        blank=True, help_text="Text answer or JSON for complex answers"
                    ),
                ),
                (
                    "answer_json",
                    models.JSONField(
                        blank=True, help_text="Structured answer data", null=True
                    ),
                ),
                (
                    "answer_file",
                    models.CharField(
                        blank=True, help_text="Path to uploaded file", max_length=500
                    ),
                ),
                (
                    "points_earned",
                    models.IntegerField(
                        default=0, help_text="Points earned for this answer"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        blank=True,
                        help_text="Has reviewer approved this answer?",
                        null=True,
                    ),
                ),
                (
                    "reviewer_comment",
                    models.TextField(
                        blank=True, help_text="Reviewer's comment on this answer"
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["question__order"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'HIPAA Security Assessment')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="What this assessment covers"),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("hipaa_security", "HIPAA Security Rule"),
                            ("hipaa_privacy", "HIPAA Privacy Rule"),
                            ("general_security", "General Security"),
                            ("soc2", "SOC 2 Compliance"),
                            ("vendor_risk", "Vendor Risk Assessment"),
                            ("custom", "Custom Assessment"),
                        ],
                        default="vendor_risk",
                        help_text="Type of compliance assessment",
                        max_length=50,
                    ),
                ),
                (
                    "total_points",
                    models.IntegerField(
                        default=100, help_text="Maximum possible score"
                    ),
                ),
                (
                    "passing_score",
                    models.IntegerField(default=70, help_text="Minimum score to pass"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this template currently in use?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(help_text="The actual question to ask"),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        help_text="Additional guidance for answering this question",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("yes_no", "Yes/No"),
                            ("multiple_choice", "Multiple Choice"),
                            ("text", "Text Response"),
                            ("number", "Numeric Response"),
                            ("date", "Date Response"),
                            ("file", "File Upload Required"),
                        ],
                        default="yes_no",
                        max_length=20,
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        help_text="Choices for multiple choice questions",
                        null=True,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=1,
                        help_text="Points for correct/compliant answer",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "correct_answer",
                    models.JSONField(
                        blank=True,
                        help_text="What answer gives full points (for auto-scoring)",
                        null=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Section/category of the question",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order within the assessment"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Must this question be answered?"
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a critical compliance question?",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
