# Generated by Django 5.2.6 on 2025-09-12 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("organizations", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="assessments.assessment",
            ),
        ),
        migrations.AddField(
            model_name="assessmenttemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessmenttemplate",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization that created this template",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_templates",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessments",
                to="assessments.assessmenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessments.assessmenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="assessments.question",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assessmenttemplate",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="assessmentresponse",
            unique_together={("assessment", "question")},
        ),
    ]
