# Generated by Django 5.2.6 on 2025-09-12 14:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="mdi-folder", max_length=50)),
                ("color", models.CharField(default="#034c81", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Document Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#2ca3fa", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the document", max_length=255
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("baa", "Business Associate Agreement"),
                            ("insurance_coi", "Certificate of Insurance"),
                            ("license", "Professional License"),
                            ("certification", "Certification"),
                            ("contract", "Contract"),
                            ("other", "Other"),
                        ],
                        help_text="Type of compliance document",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload document (PDF, Word, Excel, or image files)",
                        upload_to="documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "jpg",
                                    "png",
                                    "xlsx",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        editable=False, help_text="File size in bytes"
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Document version number"),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        default=True, help_text="Is this the current version?"
                    ),
                ),
                (
                    "version_notes",
                    models.TextField(
                        blank=True, help_text="What changed in this version?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("pending_review", "Pending Review"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_review",
                        help_text="Current status of the document",
                        max_length=20,
                    ),
                ),
                (
                    "document_date",
                    models.DateField(help_text="Date on the document itself"),
                ),
                (
                    "expires_at",
                    models.DateField(
                        blank=True,
                        help_text="When this document expires (if applicable)",
                        null=True,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this document"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this document been verified by admin?",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to parent document for versioning",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vendors.vendor",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Document category for organization",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.documentcategory",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags for flexible filtering",
                        related_name="documents",
                        to="documents.documenttag",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("download", "Downloaded"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("share", "Shared"),
                            ("upload", "Uploaded"),
                            ("verify", "Verified"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "user_agent",
                    models.TextField(help_text="Browser/client information"),
                ),
                (
                    "access_reason",
                    models.TextField(
                        blank=True, help_text="Reason for accessing PHI (if applicable)"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Django session ID for tracking",
                        max_length=40,
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changes_made",
                    models.JSONField(
                        blank=True,
                        help_text="JSON record of what was changed",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_access_logs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accessed_at"],
                "permissions": [
                    ("can_view_all_logs", "Can view all access logs"),
                    ("can_export_logs", "Can export access logs"),
                ],
                "indexes": [
                    models.Index(
                        fields=["document", "-accessed_at"],
                        name="documents_d_documen_af41d8_idx",
                    ),
                    models.Index(
                        fields=["user", "-accessed_at"],
                        name="documents_d_user_id_64228f_idx",
                    ),
                    models.Index(
                        fields=["organization", "-accessed_at"],
                        name="documents_d_organiz_4e11a8_idx",
                    ),
                    models.Index(
                        fields=["access_type", "-accessed_at"],
                        name="documents_d_access__a48768_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["vendor", "document_type"],
                name="documents_d_vendor__e08b18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "expires_at"], name="documents_d_status_fc24cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "-uploaded_at"],
                name="documents_d_organiz_98e0b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_latest", "-uploaded_at"],
                name="documents_d_is_late_95bbdb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("parent_document", "version")},
        ),
    ]
