# Generated by Django 5.2.6 on 2025-09-10 08:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("baa", "Business Associate Agreement"),
                            ("insurance_coi", "Certificate of Insurance"),
                            ("license", "Professional License"),
                            ("certification", "Certification"),
                            ("contract", "Contract"),
                            ("other", "Other"),
                        ],
                        help_text="Type of compliance document",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload document (PDF, Word, Excel, or image files)",
                        upload_to="documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "jpg",
                                    "png",
                                    "xlsx",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        editable=False, help_text="File size in bytes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("pending_review", "Pending Review"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_review",
                        help_text="Current status of the document",
                        max_length=20,
                    ),
                ),
                (
                    "document_date",
                    models.DateField(help_text="Date on the document itself"),
                ),
                (
                    "expires_at",
                    models.DateField(
                        blank=True,
                        help_text="When this document expires (if applicable)",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the document", max_length=255
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "document_type"],
                        name="documents_d_vendor__e08b18_idx",
                    ),
                    models.Index(
                        fields=["status", "expires_at"],
                        name="documents_d_status_fc24cb_idx",
                    ),
                ],
            },
        ),
    ]
