# Generated by Django 5.2.6 on 2025-09-09 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Organization name", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly unique identifier", unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Primary contact phone", max_length=20),
                ),
                ("address", models.TextField(help_text="Full address")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this organization can access the system",
                    ),
                ),
                (
                    "hipaa_agreement_signed",
                    models.BooleanField(
                        default=False,
                        help_text="Has signed HIPAA Business Associate Agreement",
                    ),
                ),
                (
                    "hipaa_agreement_date",
                    models.DateField(
                        blank=True, help_text="Date HIPAA BAA was signed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("staff", "Staff Member"),
                            ("viewer", "Read-Only Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "user"],
                "unique_together": {("user", "organization")},
            },
        ),
    ]
